name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    
    - name: Install Flatbuffers
      run: |
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers/
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DCMAKE_INSTALL_PREFIX=/usr
        make
        sudo make install
    
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: install
        directory: build
        meson-version: 0.53.0
#         options: 
        
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
#       with:
#         limit-access-to-actor: true
